on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    name: release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc-mingw-w64-x86-64

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          components: clippy
          override: true
          target: x86_64-unknown-linux-gnu

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: cache dependencies
        uses: Swatinem/rust-cache@v2.7.5

      - name: clippy check
        uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

      - name: install cargo-license
        uses: actions-rs/cargo@v1.0.3
        with:
          command: install
          args: cargo-license

      - name: compile for unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --no-run --locked

      - name: unit test
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu

      - uses: actions-rs/cargo@v1.0.3
        with:
          command: build
          args: --release --target x86_64-pc-windows-gnu

      - run: |
          mkdir nichijid-rs
          cargo license \
            --authors \
            --do-not-bundle \
            --avoid-dev-deps \
            --avoid-build-deps \
            --filter-platform x86_64-pc-windows-gnu \
              > nichijid-rs/CREDITS
          VERSION_NAME=${GITHUB_REF##*/}
          if [[ $VERSION_NAME == "master" ]]; then
              VERSION_NAME=$(git rev-parse --short HEAD)
          elif [[ ${VERSION_NAME:0:1} == "v" ]]; then
              VERSION_NAME=${VERSION_NAME:1}
          fi
          echo "$VERSION_NAME" > nichijid-rs/VERSION.txt
          cp LICENSE README.md nichijid-rs/
          cp target/x86_64-pc-windows-gnu/release/nichijid-rs.exe nichijid-rs/
          zip -r nichijid-rs-windows.zip nichijid-rs
          rm nichijid-rs/*.exe
          cargo license \
            --authors \
            --do-not-bundle \
            --avoid-dev-deps \
            --avoid-build-deps \
            --filter-platform x86_64-unknown-linux-gnu \
              > nichijid-rs/CREDITS
          cp target/x86_64-unknown-linux-gnu/release/nichijid-rs nichijid-rs/
          zip -r nichijid-rs-linux.zip nichijid-rs

      - name: pre-release
        uses: softprops/action-gh-release@v2.0.8
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          files: |
            nichijid-rs-windows.zip
            nichijid-rs-linux.zip

      - name: tagged-release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            nichijid-rs-windows.zip
            nichijid-rs-linux.zip

      - uses: docker/setup-buildx-action@v3.10.0

      - uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create tagname
        id: tagname
        run: |
          VERSION="$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')"
          # 2193: ${{ github.ref }} will replaced by GitHub Actions
          # shellcheck disable=SC2193
          [[ "${{ github.ref }}" == refs/tags/* ]] && VERSION="${VERSION/v/}"
          [[ "$VERSION" == "master" ]] && VERSION=latest
          # shellcheck disable=SC2193
          [[ "${{ github.ref }}" == refs/pull/* ]] && VERSION=dontpush
          echo "$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build and Push
        uses: docker/build-push-action@v6.15.0
        if: "! startsWith(github.ref, 'refs/pull/')"
        with:
          context: .
          platforms: linux/amd64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/yanorei32/nichijid-rs:${{ steps.tagname.outputs.version }}

      - name: Build and Push
        uses: docker/build-push-action@v6.15.0
        if: "startsWith(github.ref, 'refs/pull/')"
        with:
          context: .
          platforms: linux/amd64
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/yanorei32/nichijid-rs:${{ steps.tagname.outputs.version }}
